#!/usr/bin/env bash
CHTS_FILES_DIRECTORY=~/
CHTS_FILES_DIRECTORY_PATTERN=".*chst"

ACTIONS_KEY=key
ACTIONS_TYPE=type

# Remove font
# rofi -i -font "ypn envypn 13"

run_rofi () {
	rofi -i \
  -separator-style none -columns 1 -bw 0 \
       -line-margin 0 -line-padding 2 \
      -hide-scrollbar \
      -color-window "#222222, #222222, #b1b4b3" \
      -color-normal "#262626, #b1b4b3, #262626, #262626, #42E66C" \
      -color-active "#222222, #E356A7, #222222, #007763, #b1b4b3" \
      -color-urgent "#222222, #b1b4b3, #222222, #77003d, #b1b4b3" \
      -kb-row-select "Tab" -kb-row-tab "" \
  -lines 15 -width 1000 -dmenu -p "> " "$@"
}

addCht () {
	category=$(xsel | head -n1 | run_rofi -mesg "Insert primary category (cheatsheet file)")
	if [[ $? -eq 1 ]]; then
		exit
	fi
	subcategory=$(run_rofi -mesg "Insert subcategory")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	command=$(run_rofi -mesg "Insert key combinantion or command")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	description=$(run_rofi -mesg "Insert short description")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	action=$(run_rofi -mesg "Insert action type (key or type)")
	if [[ $? -eq 1 ]]; then
		exit
	fi

 run_rofi -mesg "Follwoing item will be added: $category $subcategory $command $description $action"

}


delete () {
	number=$1
}

edit () {
	id=$(echo $1 | tr '.' '\n' | head -n1)
}

triggerChtAction () {
	selection=$1
  chts_raw=$2

	cht_id=$(echo $selection | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
	sellected_action=$(echo ${chts_raw[$cht_id]} | awk -F"=/|=" 'NF == 2 { $0 = $0 "No tag" }; {  print $9}')
	sellected_command=$(echo ${chts_raw[$cht_id]} | awk -F"=/|=" 'NF == 2 { $0 = $0 "No tag" }; {  print $5}')

	if [[ "$sellected_action" == *$ACTIONS_KEY* ]]; then
	  xdotool $sellected_action $sellected_command
	elif [[ "$sellected_action" == *$ACTIONS_TYPE* ]]; then
		xdotool $sellected_action "$sellected_command"
	fi
}

main () {
declare -a chts_raw

#!/usr/bin/env bash
CHTS_FILES_DIRECTORY=~/.chst/*
CHTS_FILES_DIRECTORY_PATTERN=".*chst"
#for dir in $(find salford_* -type d);do

for f in $(find $CHTS_FILES_DIRECTORY/$CHTS_FILES_DIRECTORY_PATTERN -maxdepth 0 -mindepth 0 -type d);
do
	echo reading file $f
	if  ! { [[ "$f" == *"LICENSE"* ]] || [[ "$f" == *"README"* ]] || [[ "$f" == *"\."* ]] ; }  then
		readarray -t chts_tmp < $f
	fi

	chts_raw=("${chts_raw[@]}" "${chts_tmp[@]}")
done

for i in "${!chts_raw[@]}"; do
	chts_output_tmp=$chts_output_tmp"\n"${i}"=|="${chts_raw[$i]}
done

selection=$(echo -e $chts_output_tmp | awk -F"=/|=" ' {  print $1"\t"$3"\t"$5"\t"$7"\t\t"$9"\t"$11}' | run_rofi -kb-custom-1 "${new_chst}" -kb-custom-2 "${list_chst_subcat}" -kb-custom-3 "${delete_chst}" -kb-custom-4 "${edit_chst}" -mesg "Enter to select a chst item. Alt+n to create a new one.
Edit a chst item with Alt+e. Remove one with Alt+d. Search for subcatgories with Alt+t.")

val=$?

	if [[ $val -eq 1 ]]; then
		exit
	elif [[ $val -eq 10 ]]; then
		addCht
	elif [[ $val -eq 11 ]]; then
		listTags
	elif [[ $val -eq 12 ]]; then
		delete $selection
	elif [[ $val -eq 13 ]]; then
		edit $selection
	else
		triggerChtAction $selection $chts_raw
	fi



}


#shortcuts
new_chst="Alt+n"
list_chst_subcat="Alt+t"
delete_chst="Alt+d"
edit_chst="Alt+e"


main
