#!/usr/bin/env bash
#---------------------------------------------------------------------------
#--                                                                       --
#--
#--    _|_|_|      _|_|_|  _|    _|    _|_|_|  _|_|_|_|_|
#--    _|    _|  _|        _|    _|  _|            _|
#--    _|_|_|    _|        _|_|_|_|    _|_|        _|
#--    _|    _|  _|        _|    _|        _|      _|
#--    _|    _|    _|_|_|  _|    _|  _|_|_|        _|
#--                                                                       --
#---------------------------------------------------------------------------

#---------------------------------------------------------------------------
#-- TODO
#---------------------------------------------------------------------------

# GENERAL
# *

# NON CHST SPECIFIC
# *

# ACTIVE
# * Fix tabulation after the command - spacing between end of command and description is not fixed

# DEFER (should do but uncertain how to solve after initial cursory review, so will defer till have more time to research)
# *

#DONE
# * Priotitize personal chst files loading ( ~/.pchst ) over general ( ~/.chst )

# TESTED/REJECTED/WONTFIX



CHTS_DIRECTORY=~
CHTS_FILES=.chst
PERSONAL_CHTS_FILES=.pchst

ACTION_KEY=key
ACTION_TYPE=type
ACTION_TYPE=input+key
#RCHST_DOTFILE=~/.rchst

# if [ -f "$RCHST_DOTFILE" ]
# then
#  . $RCHST_DOTFILE
# fi



# Remove font
# rofi -i -font "ypn envypn 13"

run_rofi () {
	rofi -i -separator-style none -columns 1 -bw 0 \
       -line-margin 0 -line-padding 2 \
      -hide-scrollbar \
      -color-window "#222222, #222222, #b1b4b3" \
      -color-normal "#262626, #b1b4b3, #262626, #262626, #42E66C" \
      -color-active "#222222, #E356A7, #222222, #007763, #b1b4b3" \
      -color-urgent "#222222, #b1b4b3, #222222, #77003d, #b1b4b3" \
      -kb-row-select "Tab" -kb-row-tab "" \
  -lines 15 -width 1000 -dmenu -p "> " "$@"


}

addCht () {
	category=$(xsel | head -n1 | run_rofi -mesg "Insert primary category (cheatsheet file)")
	if [[ $? -eq 1 ]]; then
		exit
	fi
	subcategory=$(run_rofi -mesg "Insert subcategory")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	command=$(run_rofi -mesg "Insert key combinantion or command")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	description=$(run_rofi -mesg "Insert short description")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	action=$(run_rofi -mesg "Insert action type (key or type)")
	if [[ $? -eq 1 ]]; then
		exit
	fi

 run_rofi -mesg "Follwoing item will be added: $category $subcategory $command $description $action"

}


delete () {
	number=$1
}

edit () {
	id=$(echo $1 | tr '.' '\n' | head -n1)
}

triggerChtAction () {
	selection=$1
  chts_raw=$2

	cht_id=$(echo $selection | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
	sellected_action=$(echo ${chts_raw[$cht_id]} | awk -F"=/|=" 'NF == 2 { $0 = $0 "No tag" }; {  print $9}')
	sellected_command=$(echo ${chts_raw[$cht_id]} | awk -F"=/|=" 'NF == 2 { $0 = $0 "No tag" }; {  print $5}')

	if [[ "$sellected_action" == *$ACTION_KEY* ]]; then
	  xdotool $sellected_action --clearmodifiers $sellected_command
	elif [[ "$sellected_action" == *$ACTION_TYPE* ]]; then
		xdotool $sellected_action "$sellected_command"
	fi
}

main () {
declare -a chts_raw=()
declare -a chts_files=()

#!/usr/bin/env bash
# CHTS_DIRECTORY=~/
# CHTS_FILES=.chst/*
# PERSONAL_CHTS_FILES=.pchst/*

for f in $CHTS_DIRECTORY/{$PERSONAL_CHTS_FILES,$CHTS_FILES}/*
do
	declare -a chts_tmp=()
	if  ! { [[ "$f" == *"LICENSE"* ]] || [[ "$f" == *"README"* ]] || [[ "$f" == *"\."* ]] ; }  then
    fileName=$(basename -- "$f")
		inarray=$(echo ${chts_files[@]} | grep -o $fileName | wc -l)
		if [[ $inarray -eq 0 ]]; then
			chts_files+=($fileName)
			readarray -t chts_tmp < $f
			echo "Reading from:"$f
		fi
	fi
	chts_raw=("${chts_raw[@]}" "${chts_tmp[@]}")
done

echo ${chts_raw[@]}

for i in "${!chts_raw[@]}"; do
	chts_output_tmp=$chts_output_tmp"\n"${i}"=|="${chts_raw[$i]}
done

selection=$(echo -e $chts_output_tmp | awk -F"=/|=" ' {  print $1"\t"$3"\t"$5"\t"$7"\t\t"$9"\t"$11}' | run_rofi -kb-custom-1 "${new_chst}" -kb-custom-2 "${list_chst_subcat}" -kb-custom-3 "${delete_chst}" -kb-custom-4 "${edit_chst}" -mesg "Enter to select a chst item. Alt+n to create a new one.
Edit a chst item with Alt+e. Remove one with Alt+d. Search for subcatgories with Alt+t.")

val=$?

	if [[ $val -eq 1 ]]; then
		exit
	elif [[ $val -eq 10 ]]; then
		addCht
	elif [[ $val -eq 11 ]]; then
		listTags
	elif [[ $val -eq 12 ]]; then
		delete $selection
	elif [[ $val -eq 13 ]]; then
		edit $selection
	else
		triggerChtAction $selection $chts_raw
	fi



}


#shortcuts
new_chst="Alt+n"
list_chst_subcat="Alt+t"
delete_chst="Alt+d"
edit_chst="Alt+e"


main
